[flint]
name = "RIPPLE"

[shards]
installed = [
  { name = "flint", remote = "NUU-Cognition/shard-flint" },
  { name = "orbh", remote = "NUU-Cognition/shard-orbh" },
]
dev-remote = []
dev-local = []

[references]
codebases = [
  { name = "RIPPLE" },
]
